# Generated by Django 5.2.17 on 2026-08-29 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadarSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, verbose_name="名称")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("arxiv", "arXiv"),
                            ("github", "GitHub"),
                            ("huggingface", "Hugging Face"),
                            ("openreview", "OpenReview"),
                        ],
                        max_length=24,
                        unique=True,
                        verbose_name="来源类型",
                    ),
                ),
                ("homepage_url", models.URLField(verbose_name="主页")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="启用")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disabled", "未启用"),
                            ("idle", "待同步"),
                            ("running", "同步中"),
                            ("success", "正常"),
                            ("error", "异常"),
                        ],
                        default="disabled",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后成功时间"
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后失败时间"
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="最后错误摘要"
                    ),
                ),
            ],
            options={
                "verbose_name": "雷达来源",
                "verbose_name_plural": "雷达来源",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                            ("skipped", "已跳过"),
                        ],
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "inserted_count",
                    models.PositiveIntegerField(default=0, verbose_name="新增"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="更新"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="跳过"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="错误"),
                ),
                (
                    "error_summary",
                    models.TextField(blank=True, verbose_name="错误摘要"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_runs",
                        to="radar.radarsource",
                        verbose_name="来源",
                    ),
                ),
            ],
            options={
                "verbose_name": "采集记录",
                "verbose_name_plural": "采集记录",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="RadarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(max_length=200, verbose_name="外部 ID"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("paper", "论文"),
                            ("repository", "开源项目"),
                            ("model", "模型"),
                            ("article", "文章"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                (
                    "original_url",
                    models.URLField(max_length=500, verbose_name="原文链接"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "ai_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="AI 摘要"),
                ),
                (
                    "authors",
                    models.JSONField(blank=True, default=list, verbose_name="作者"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="来源元数据"
                    ),
                ),
                ("published_at", models.DateTimeField(verbose_name="来源发布时间")),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="抓取时间"),
                ),
                (
                    "relevance_score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="相关性"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="精选"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="公开")),
                (
                    "is_demo",
                    models.BooleanField(default=False, verbose_name="演示数据"),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="radar_items", to="core.topic"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="radar.radarsource",
                        verbose_name="来源",
                    ),
                ),
            ],
            options={
                "verbose_name": "雷达条目",
                "verbose_name_plural": "雷达条目",
                "ordering": ("-published_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["is_visible", "published_at"],
                        name="radar_radar_is_visi_d7f67a_idx",
                    ),
                    models.Index(
                        fields=["kind", "published_at"],
                        name="radar_radar_kind_bfeca8_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="radar_unique_source_external_id",
                    )
                ],
            },
        ),
    ]
