# Generated by Django 5.2.17 on 2026-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="radarsource",
            name="last_attempt_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后尝试时间"
            ),
        ),
        migrations.AddField(
            model_name="radarsource",
            name="last_item_count",
            field=models.PositiveIntegerField(default=0, verbose_name="最近条目数"),
        ),
        migrations.AddField(
            model_name="radarsource",
            name="sync_state",
            field=models.JSONField(blank=True, default=dict, verbose_name="同步状态"),
        ),
        migrations.AlterField(
            model_name="radaritem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("paper", "论文"),
                    ("repository", "开源项目"),
                    ("model", "模型"),
                    ("dataset", "数据集"),
                    ("article", "文章"),
                ],
                max_length=20,
                verbose_name="类型",
            ),
        ),
        migrations.AlterField(
            model_name="radarsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("arxiv", "arXiv"),
                    ("github", "GitHub"),
                    ("huggingface", "Hugging Face"),
                    ("deepseek", "DeepSeek AI Search"),
                    ("openreview", "OpenReview"),
                ],
                max_length=24,
                unique=True,
                verbose_name="来源类型",
            ),
        ),
    ]
