# Generated by Django 5.2.17 on 2026-08-29 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="名称"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="标识"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=240, verbose_name="描述"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "文章分类",
                "verbose_name_plural": "文章分类",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="标识"),
                ),
                ("summary", models.TextField(verbose_name="摘要")),
                ("body_markdown", models.TextField(verbose_name="Markdown 正文")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "reading_minutes",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="阅读分钟数"
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(blank=True, verbose_name="相关代码"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="精选"),
                ),
                (
                    "is_demo",
                    models.BooleanField(default=False, verbose_name="演示数据"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO 标题"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="SEO 描述"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="core.topic"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="blog.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ("-published_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"],
                        name="blog_articl_status_8b18ca_idx",
                    ),
                    models.Index(
                        fields=["category", "status", "published_at"],
                        name="blog_articl_categor_8afef1_idx",
                    ),
                ],
            },
        ),
    ]
