# Generated by Django 5.2.17 on 2026-08-29 13:31

import apps.blog.models
import apps.blog.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_note_hierarchy(apps, _schema_editor):
    category = apps.get_model("blog", "Category")

    def get_or_create_category(*, slug, name, parent=None, sort_order=0):
        instance = category.objects.filter(slug=slug).first()
        if instance is None:
            instance = category.objects.filter(name=name).first()
        if instance is None:
            instance = category.objects.create(
                slug=slug,
                name=name,
                parent=parent,
                sort_order=sort_order,
            )
        elif instance.parent_id is None and parent is not None:
            instance.parent = parent
            instance.save(update_fields=("parent", "updated_at"))
        return instance

    ai = get_or_create_category(slug="ai-technology", name="AI 技术", sort_order=10)
    models_category = get_or_create_category(
        slug="large-models",
        name="大模型",
        parent=ai,
        sort_order=10,
    )
    inference = get_or_create_category(
        slug="inference-optimization",
        name="推理优化",
        parent=models_category,
        sort_order=10,
    )
    get_or_create_category(
        slug="notes",
        name="学习笔记",
        parent=inference,
        sort_order=10,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        max_length=240,
                        storage=apps.blog.storage.NoteSourceStorage(),
                        upload_to=apps.blog.models.note_source_upload_to,
                        verbose_name="原始文件",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=240, verbose_name="原文件名"),
                ),
                (
                    "source_format",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("docx", "Word DOCX"),
                            ("pdf", "PDF"),
                        ],
                        max_length=16,
                        verbose_name="文件格式",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(max_length=120, verbose_name="内容类型"),
                ),
                ("size_bytes", models.PositiveBigIntegerField(verbose_name="文件大小")),
                (
                    "sha256",
                    models.CharField(max_length=64, unique=True, verbose_name="SHA-256"),
                ),
                (
                    "outline",
                    models.JSONField(blank=True, default=list, verbose_name="文章目录"),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="提取时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "笔记源文件",
                "verbose_name_plural": "笔记源文件",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="blog.category",
                verbose_name="上级分类",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "sort_order", "name"],
                name="blog_catego_parent__df2da1_idx",
            ),
        ),
        migrations.AddField(
            model_name="articlesourcefile",
            name="article",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_file",
                to="blog.article",
                verbose_name="文章",
            ),
        ),
        migrations.RunPython(seed_note_hierarchy, migrations.RunPython.noop),
    ]
