# Generated by Django 5.2.17 on 2026-08-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, verbose_name="姓名")),
                (
                    "english_name",
                    models.CharField(blank=True, max_length=120, verbose_name="英文名"),
                ),
                (
                    "headline",
                    models.CharField(max_length=180, verbose_name="一句话介绍"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="个人简介")),
                (
                    "affiliation",
                    models.CharField(max_length=180, verbose_name="学校/机构"),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=120, verbose_name="身份"),
                ),
                (
                    "research_focus",
                    models.CharField(max_length=240, verbose_name="研究方向"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="联系邮箱"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="SEO 描述"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
            ],
            options={
                "verbose_name": "个人档案",
                "verbose_name_plural": "个人档案",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="名称"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="标识"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=240, verbose_name="描述"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#315CFF", max_length=20, verbose_name="颜色"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "研究主题",
                "verbose_name_plural": "研究主题",
                "ordering": ("sort_order", "name"),
            },
        ),
    ]
