# Generated by Django 5.2.17 on 2026-08-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="标识"),
                ),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=200, verbose_name="副标题"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("inference", "推理优化"),
                            ("system", "系统实践"),
                            ("tool", "工具"),
                            ("learning", "学习实验"),
                        ],
                        default="inference",
                        max_length=24,
                        verbose_name="分类",
                    ),
                ),
                ("summary", models.TextField(verbose_name="摘要")),
                ("problem", models.TextField(blank=True, verbose_name="研究问题")),
                ("approach", models.TextField(blank=True, verbose_name="设计思路")),
                ("contribution", models.TextField(blank=True, verbose_name="个人贡献")),
                ("outcome", models.TextField(blank=True, verbose_name="结果")),
                (
                    "repository_url",
                    models.URLField(blank=True, verbose_name="代码仓库"),
                ),
                ("demo_url", models.URLField(blank=True, verbose_name="演示链接")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="精选"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="公开"),
                ),
                (
                    "is_demo",
                    models.BooleanField(default=False, verbose_name="演示数据"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "started_at",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "ended_at",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="core.topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ("sort_order", "-updated_at"),
                "indexes": [
                    models.Index(
                        fields=["is_published", "is_featured", "sort_order"],
                        name="portfolio_p_is_publ_375d84_idx",
                    )
                ],
            },
        ),
    ]
