# Generated by Django 5.2.17 on 2026-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="外部 ID"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="external_source",
            field=models.CharField(
                choices=[("manual", "手工维护"), ("github", "GitHub")],
                default="manual",
                max_length=24,
                verbose_name="外部来源",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后同步时间"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source_metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="来源元数据"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("external_source", "external_id"),
                name="portfolio_unique_external_project",
            ),
        ),
    ]
