[CmdletBinding()]
param(
    [string]$OutputPath = 'deploy\mysql\schema.sql'
)

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location -LiteralPath $projectRoot

$composeFiles = @('compose.yaml', 'compose.dev.yaml')
$containerId = [string](& docker compose -f $composeFiles[0] -f $composeFiles[1] ps -q db)
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($containerId)) {
    throw 'The local MySQL container is not running. Start it with docker compose before exporting.'
}

if ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $resolvedOutputPath = [System.IO.Path]::GetFullPath($OutputPath)
}
else {
    $resolvedOutputPath = [System.IO.Path]::GetFullPath((Join-Path $projectRoot $OutputPath))
}

$outputDirectory = Split-Path -Parent $resolvedOutputPath
if ([string]::IsNullOrWhiteSpace($outputDirectory)) {
    throw 'OutputPath must include a valid directory.'
}
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null

$temporaryPath = "$resolvedOutputPath.tmp"
$dumpCommand = @'
MYSQL_PWD="$MYSQL_PASSWORD" exec mysqldump \
  -h 127.0.0.1 \
  -u"$MYSQL_USER" \
  --no-data \
  --single-transaction \
  --skip-lock-tables \
  --routines \
  --events \
  --triggers \
  --no-tablespaces \
  --default-character-set=utf8mb4 \
  "$MYSQL_DATABASE"
'@

try {
    $schemaLines = & docker compose -f $composeFiles[0] -f $composeFiles[1] `
        exec -T db sh -c $dumpCommand
    if ($LASTEXITCODE -ne 0) {
        throw 'mysqldump failed; the previous schema file was left unchanged.'
    }
    if ($null -eq $schemaLines -or $schemaLines.Count -eq 0) {
        throw 'mysqldump returned an empty schema; the previous schema file was left unchanged.'
    }

    $header = @(
        '-- SS-LAB MySQL schema snapshot.',
        '-- Generated by scripts/export-database-schema.ps1; do not edit manually.',
        '-- Django migrations are the source of truth. This file contains no credentials.',
        ''
    )
    $schemaText = [string]::Join(
        [Environment]::NewLine,
        @($header + $schemaLines + '')
    )
    [System.IO.File]::WriteAllText(
        $temporaryPath,
        $schemaText,
        [System.Text.UTF8Encoding]::new($false)
    )
    Move-Item -LiteralPath $temporaryPath -Destination $resolvedOutputPath -Force
}
finally {
    if (Test-Path -LiteralPath $temporaryPath) {
        Remove-Item -LiteralPath $temporaryPath -Force
    }
}

Write-Host "Schema exported to $resolvedOutputPath" -ForegroundColor Green
